const blogTypes = {
    ADD_BLOG: "ADD_BLOG",
    UPLOAD_IMG: "UPLOAD_IMG",
    UPDATE_BLOG: "UPDATE_BLOG",
    REMOVE_BLOG: "REMOVE_BLOG",
    REMOVE_BLOG_REDUX: 'REMOVE_BLOG_REDUX',
    REMOVE_BLOGS: "REMOVE_BLOGS",
    DELETE_IMG: "DELETE_IMG",
    SHOW_BLOG: "SHOW_BLOG",
    SHOW_BLOGS: "SHOW_BLOGS",
    BLOG_ERROR: "BLOG_ERROR"
};

export default blogTypes;