const expTypes = {
    ADD_EXP: "ADD_EXP",
    UPLOAD_IMG: "UPLOAD_IMG",
    UPLOAD_BIMG: "UPLOAD_BIMG",
    UPLOAD_GIF: "UPLOAD_GIF",
    UPDATE_EXP: "UPDATE_EXP",
    REMOVE_EXP: "REMOVE_EXP",
    REMOVE_EXP_REDUX: 'REMOVE_EXP_REDUX',
    REMOVE_EXPS: "REMOVE_EXPS",
    DELETE_IMG: "DELETE_IMG",
    SHOW_EXP: "SHOW_EXP",
    SHOW_EXPS: "SHOW_EXPS",
    EXP_ERROR: "EXP_ERROR"
};

export default expTypes;