const codeTypes = {
    ADD_CODE: "ADD_CODE",
    UPLOAD_BIMG: "UPLOAD_BIMG",
    UPLOAD_GIF: "UPLOAD_GIF",
    UPDATE_CODE: "UPDATE_CODE",
    REMOVE_CODE: "REMOVE_CODE",
    REMOVE_CODE_REDUX: 'REMOVE_CODE_REDUX',
    REMOVE_CODES: "REMOVE_CODES",
    DELETE_IMG: "DELETE_IMG",
    SHOW_CODE: "SHOW_CODE",
    SHOW_CODES: "SHOW_CODES",
    CODE_ERROR: "CODE_ERROR"
};

export default codeTypes;