const authTypes = {
    ADMIN_LOADED: 'ADMIN_LOADED',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILD: 'LOGIN_FAILD',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    UPDATE_SUCCESS: 'UPDATE_SUCCESS',
    SHOW_ADMINS: 'SHOW_ADMINS',
    SHOW_ADMIN: 'SHOW_ADMIN',
    ADMINS_ERROR: 'ADMINS_ERROR',
    DELETE_SUCCESS: 'DELETE_SUCCESS',
    DELETE_ERROR: 'DELETE_ERROR',
    LOGOUT: 'LOGOUT'
}

export default authTypes;
